/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author JhéssikLeal
 */
public class Signos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signos.class.getName());

    /**
     * Creates new form Signos
     */
    public Signos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escorpiao = new javax.swing.JPanel();
        areaAbas = new javax.swing.JTabbedPane();
        inicio = new javax.swing.JPanel();
        areacompatibilidade = new javax.swing.JPanel();
        areadescobrirsigno = new javax.swing.JPanel();
        titulodescobrirsigno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        diadenacimento = new javax.swing.JLabel();
        mes = new javax.swing.JLabel();
        tfnome = new javax.swing.JTextField();
        cbdia = new javax.swing.JComboBox<>();
        cbmes = new javax.swing.JComboBox<>();
        fundoInicio = new javax.swing.JLabel();
        libra = new javax.swing.JPanel();
        fundolibras = new javax.swing.JLabel();
        aries = new javax.swing.JPanel();
        fundoaris = new javax.swing.JLabel();
        ftouro = new javax.swing.JPanel();
        fundotouro = new javax.swing.JLabel();
        cancer = new javax.swing.JPanel();
        fundocancer = new javax.swing.JLabel();
        virgem = new javax.swing.JPanel();
        fundovirgem = new javax.swing.JLabel();
        gemeos = new javax.swing.JPanel();
        fundogemeos = new javax.swing.JLabel();
        leao = new javax.swing.JPanel();
        fundoLeao = new javax.swing.JLabel();
        capricornio = new javax.swing.JPanel();
        fundocapricornio = new javax.swing.JLabel();
        aquario = new javax.swing.JPanel();
        fundolibras4 = new javax.swing.JLabel();
        sagitario = new javax.swing.JPanel();
        fundosargitario = new javax.swing.JLabel();

        javax.swing.GroupLayout escorpiaoLayout = new javax.swing.GroupLayout(escorpiao);
        escorpiao.setLayout(escorpiaoLayout);
        escorpiaoLayout.setHorizontalGroup(
            escorpiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2488, Short.MAX_VALUE)
        );
        escorpiaoLayout.setVerticalGroup(
            escorpiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1454, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaAbas.setForeground(new java.awt.Color(51, 51, 255));
        areaAbas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout areacompatibilidadeLayout = new javax.swing.GroupLayout(areacompatibilidade);
        areacompatibilidade.setLayout(areacompatibilidadeLayout);
        areacompatibilidadeLayout.setHorizontalGroup(
            areacompatibilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        areacompatibilidadeLayout.setVerticalGroup(
            areacompatibilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        inicio.add(areacompatibilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 460, 260));

        titulodescobrirsigno.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        titulodescobrirsigno.setForeground(new java.awt.Color(51, 51, 255));
        titulodescobrirsigno.setText("descubra o seu signo");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel1.setText("nome");

        diadenacimento.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        diadenacimento.setText("seu dia de nacimento");

        mes.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        mes.setText("mes de nacimento");
        mes.setToolTipText("");

        tfnome.setText("digite o seu nome");

        cbdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        cbmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", " Fevereiro", " Março", " Abril", " Maio", " Junho", " Julho", " Agosto", " Setembro", " outubro", " Novembro", " Dezembro" }));

        javax.swing.GroupLayout areadescobrirsignoLayout = new javax.swing.GroupLayout(areadescobrirsigno);
        areadescobrirsigno.setLayout(areadescobrirsignoLayout);
        areadescobrirsignoLayout.setHorizontalGroup(
            areadescobrirsignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areadescobrirsignoLayout.createSequentialGroup()
                .addGroup(areadescobrirsignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areadescobrirsignoLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(titulodescobrirsigno, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(areadescobrirsignoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(areadescobrirsignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(areadescobrirsignoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(areadescobrirsignoLayout.createSequentialGroup()
                                .addGroup(areadescobrirsignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diadenacimento)
                                    .addComponent(mes))
                                .addGap(40, 40, 40)
                                .addGroup(areadescobrirsignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        areadescobrirsignoLayout.setVerticalGroup(
            areadescobrirsignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areadescobrirsignoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titulodescobrirsigno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(areadescobrirsignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(areadescobrirsignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diadenacimento)
                    .addComponent(cbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(areadescobrirsignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mes)
                    .addComponent(cbmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        inicio.add(areadescobrirsigno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 460, 290));

        fundoInicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\zodiaco.png")); // NOI18N
        inicio.add(fundoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2382, -1));

        areaAbas.addTab("Inicio", inicio);

        libra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundolibras.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        libra.add(fundolibras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3172, 1123));

        areaAbas.addTab("Libra", libra);

        aries.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundoaris.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        aries.add(fundoaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, 1151, 840));

        areaAbas.addTab("Áries", aries);

        ftouro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundotouro.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        ftouro.add(fundotouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3172, 1123));

        areaAbas.addTab("Touro", ftouro);

        cancer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundocancer.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        cancer.add(fundocancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1551, 797));

        areaAbas.addTab("Câncer", cancer);

        virgem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundovirgem.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        virgem.add(fundovirgem, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 15, 1479, 761));

        areaAbas.addTab("Virgem", virgem);

        gemeos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundogemeos.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        gemeos.add(fundogemeos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3172, 1123));

        areaAbas.addTab("Gêmeos", gemeos);

        leao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundoLeao.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        fundoLeao.setToolTipText("");
        leao.add(fundoLeao, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 2063, 1115));

        areaAbas.addTab("Leão", leao);

        capricornio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundocapricornio.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        capricornio.add(fundocapricornio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3172, 1123));

        areaAbas.addTab("Capricórnio", capricornio);

        aquario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundolibras4.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        aquario.add(fundolibras4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3172, 1123));

        areaAbas.addTab("Aquário", aquario);

        sagitario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundosargitario.setIcon(new javax.swing.ImageIcon("C:\\Users\\EnzoLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\fundo.jpg")); // NOI18N
        sagitario.add(fundosargitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 3172, -1));

        areaAbas.addTab("Sagitário", sagitario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(areaAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 2488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(areaAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 1499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1466, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aquario;
    private javax.swing.JTabbedPane areaAbas;
    private javax.swing.JPanel areacompatibilidade;
    private javax.swing.JPanel areadescobrirsigno;
    private javax.swing.JPanel aries;
    private javax.swing.JPanel cancer;
    private javax.swing.JPanel capricornio;
    private javax.swing.JComboBox<String> cbdia;
    private javax.swing.JComboBox<String> cbmes;
    private javax.swing.JLabel diadenacimento;
    private javax.swing.JPanel escorpiao;
    private javax.swing.JPanel ftouro;
    private javax.swing.JLabel fundoInicio;
    private javax.swing.JLabel fundoLeao;
    private javax.swing.JLabel fundoaris;
    private javax.swing.JLabel fundocancer;
    private javax.swing.JLabel fundocapricornio;
    private javax.swing.JLabel fundogemeos;
    private javax.swing.JLabel fundolibras;
    private javax.swing.JLabel fundolibras4;
    private javax.swing.JLabel fundosargitario;
    private javax.swing.JLabel fundotouro;
    private javax.swing.JLabel fundovirgem;
    private javax.swing.JPanel gemeos;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel leao;
    private javax.swing.JPanel libra;
    private javax.swing.JLabel mes;
    private javax.swing.JPanel sagitario;
    private javax.swing.JTextField tfnome;
    private javax.swing.JLabel titulodescobrirsigno;
    private javax.swing.JPanel virgem;
    // End of variables declaration//GEN-END:variables
}
